/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tirardadosdnd;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Kiriel
 * @version 1.0
 */
/**
 * Ventana específicas del dado D20, esta incorpora los botones de tirar dado,
 * que hace uso del método heredado de la clase padre para "tirar" el dado una
 * vez tirado, antes de aparecer el resultado, aparece una animación de un dado
 * moviéndose y una vez termina, aparece el resultado en la área de texto,
 * también podemos guardar los resultados y mostrarlos, ya que la variable está
 * implementada como un hashmap, cada dado, tiene sus resultados propios y no
 * interfieren entre ellos
 */
public class VentanaD20 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaD4
     */
    public VentanaD20() {
        initComponents();
        jTextArea1.setEditable(false);
        jLabel1.setVisible(false);//seteo este label a false, ya que posteriormente al clicar en el botón, se hará true
    }
    int resultado = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kiriel\\Documents\\NetBeansProjects\\TirarDadosDnD\\resources\\IMG\\GIF.gif")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, 0, 1920, 640));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setText("Guardar resultado");
        jButton6.setActionCommand("Guardar");
        jButton6.setMaximumSize(new java.awt.Dimension(200, 100));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 100));
        jButton6.setPreferredSize(new java.awt.Dimension(200, 100));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("SELECCIONA UN OPCIÓN");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1380, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setText("Salir");
        jButton8.setActionCommand("salir");
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));
        jButton8.setPreferredSize(new java.awt.Dimension(200, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kiriel\\Documents\\NetBeansProjects\\TirarDadosDnD\\resources\\IMG\\D20.png")); // NOI18N
        jButton1.setText("Tirar D20");
        jButton1.setActionCommand("tirarD4");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));
        jButton1.setMaximumSize(new java.awt.Dimension(200, 100));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 100));
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(200, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, -1, -1));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setText("Volver");
        jButton9.setMaximumSize(new java.awt.Dimension(200, 100));
        jButton9.setMinimumSize(new java.awt.Dimension(200, 100));
        jButton9.setPreferredSize(new java.awt.Dimension(200, 100));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jButton10.setText("Volver");
        jButton10.setMaximumSize(new java.awt.Dimension(200, 100));
        jButton10.setMinimumSize(new java.awt.Dimension(200, 100));
        jButton10.setPreferredSize(new java.awt.Dimension(200, 100));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setText("Mostrar resultados");
        jButton11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 0)));
        jButton11.setPreferredSize(new java.awt.Dimension(200, 100));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kiriel\\Documents\\NetBeansProjects\\TirarDadosDnD\\resources\\IMG\\taverna.jpg")); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel3.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel3.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 1030));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kiriel\\Documents\\NetBeansProjects\\TirarDadosDnD\\resources\\IMG\\taverna.jpg")); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -30, 1210, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //Guardar resultado
        if (resultado == 0) {
            jTextArea1.setText("Primero tira el dado para tener un resultado y guardarlo");
        }//if
        else {
            D20.guardarResultados(resultado);
            jTextArea1.setText("Resultado guardado");
            resultado = 0;
        }//else
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //Salir
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Tirar D20
        resultado = D20.tirar();
        jTextArea1.setText("Resultado: " + resultado);

        jLabel1.setVisible(true);
        // Usar un Timer para ocultar el GIF tras 5 segundos
        Timer contador = new Timer(8000, new ActionListener() { //Creo un temporalizador para que cuando clique en el botón u ocurra el evento, se accione el código
            @Override
            public void actionPerformed(ActionEvent e) {
                jLabel1.setVisible(false); //Una vez accionado, como se ha definido que dure 8 segundos, tras los 8 segundos, este jLabel pasará a ser invisible de nuevo
            }//action
        });
        contador.setRepeats(false); //Define que se repita solo una vez
        contador.start(); //empieza a contar
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //volver a la ventana principal
        VentanaPrincipal ventanaP = new VentanaPrincipal();
        ventanaP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        //Mostrar resultados
        jTextArea1.setText(D20.muestraDeResultados());


    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaD4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaD4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaD4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaD4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaD4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
DadoD20 D20 = new DadoD20();
}//class
